name = "NeoForge Create"
author = "Sean T"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5324916ac7b630f222338086b1951fabd3756150710687c29608b61dddddcad"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
