name = "NeoForge Create"
author = "Sean T"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0caad9bb4bb5ec2b1c91e2314a2d23d48b98ce2f18dbf1568bd3db61468334ad"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
