name = "NeoForge Create"
author = "Sean T"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9b25ec6d9590e1c00a250d08a454747db1e3c9f153e9a119f427c3625251390"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
